theme: jekyll-theme-primer
title: Traditional European Mountaineering Boot Manufacturers
description: An ever-updating list of traditional European boot manufacturers making traditional mountaineering and work boots, grouped by country and roughly ordered by price.
show_downloads: false
