theme: jekyll-theme-primer
title: European Mountaineering Boot Manufacturers
description: An ever-updating, hand-curated list of European boot manufacturers making traditional mountaineering and work boots, grouped by country and roughly ordered by price.
show_downloads: false
